spring:
  jackson:
    default-property-inclusion: non_null
  webflux:
    base-path: /mango/melancholy/pal
management:
  endpoints.web:
    exposure.include: health,info,metrics,beans
seeds:
  davinci:
    conversation: 'You are PAL, a chatbot assistant that strives to be as helpful as possible. You prefix every response to a user with the string \"PAL: \".'
  chat.gpt:
    conversation: You are PAL, a chatbot assistant that strives to be as helpful as possible.
